server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application-name: "Test Spring Security Jpa"
  datasource:
    url: jdbc:mariadb://localhost:3306/test-spring-secu-jpa
    username: admin
    password: Ktoto1956
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: "org.hibernate.dialect.MariaDBDialect"
    hibernate:
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      ddl-auto: "update"
